
build: false

clone_depth: 10

environment:
  matrix:
#    - PYTHON_VERSION: 3.6
#      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3-x64
#    - PYTHON_VERSION: 3.7
#      MINICONDA: C:\Miniconda3
#    - PYTHON_VERSION: 3.7
#      MINICONDA: C:\Miniconda3-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - cmd: echo "Filesystem:"
  - dir
  # Get needed submodules
  - git submodule update --init
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy"
  - activate test-environment
  # Upgrade to the latest pip, setuptools, and wheel.
  - python -m pip install -U pip setuptools wheel

build_script:
  - python setup.py install
  - python setup.py bdist_wheel

#Looks like graphical testing is out...
#https://help.appveyor.com/discussions/problems/6946-opengl
test_script:
  #Just run the doctests
  - python lavavu/lavavu.py
#  - git clone --depth 1 https://github.com/mivp/LavaVuTesting
#  - cd LavaVuTesting
#  - python runall.py

after_test:
  # This step builds your wheels.
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

