sudo: false
language: cpp
compiler: gcc
before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi
os:
  - linux
#  - osx
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
#  - sudo apt-get update -qq
#  - sudo apt-get install -y -qq lcov curl
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  #- mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make
  - make
