language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang   
    - os: osx
      compiler: gcc 
before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CPP="g++-4.9"; CC="gcc-4.9"; echo $CPP;echo $CC ; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - python-numpy
    - libgl1-mesa-dev
    - libgl1-mesa-glx
    - xvfb
    - xserver-xephyr
    - vnc4server
before_script:
  - git clone https://github.com/mivp/LavaVuTesting
  - sudo pip install pyvirtualdisplay
  - export PYTHONPATH=$PYTHONPATH:`pwd`
script:
  - make -j4
  - cd LavaVuTesting
  - python runall.py xvfb
after_script:
  - ls -la ./bin
