language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang   
    - os: osx
      compiler: gcc 
before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-4.9"; CC="gcc-4.9"; echo $CXX;echo $CC ; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - python-numpy
    - libgl1-mesa-dev
    - libgl1-mesa-glx
before_script:
  - git clone https://github.com/mivp/LavaVuTesting
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - export PYTHONPATH=$PYTHONPATH:`pwd`
script:
  - make -j2
  - cd LavaVuTesting
  - python runall.py echo
after_script:
  - ls -la ./bin
