language: python
dist: trusty
sudo: false
notifications:
  slack: cavedev:0TKfIim9KQnrmiKExKFnKT9L
matrix:
  include:
    - python: "2.7"
      os: linux
      compiler: gcc
      before_script:
        - export CXX="g++-4.9";
        - export CC="gcc-4.9";
      install: pip install numpy
    - python: "3.6"
      os: linux
      compiler: gcc
      before_script:
        - export CXX="g++-4.9";
        - export CC="gcc-4.9";
      install: pip install numpy
    - os: osx
      compiler: clang   
      install: pip install numpy
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libgl1-mesa-dri
    - libgl1-mesa-glx
    - libgl1-mesa-dev
script:
  - make -j2
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export PYTHONPATH=$PYTHONPATH:`pwd`;
      git clone --depth 1 https://github.com/mivp/LavaVuTesting;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
      cd LavaVuTesting;
      export DISPLAY=:99.0;
      export GALLIUM_DRIVER="llvmpipe";
      python runall.py echo verbose || travis_terminate 1;
      cd ..;
    fi
after_script:
  - pwd
  - ls -la ./bin
