language: cpp
compiler: gcc
before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi
os:
  - linux
#  - osx
install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -y -qq lcov curl
script:
  #- mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make
  - make
