language: cpp
dist: trusty
sudo: required
matrix:
  include:
    - os: linux
      compiler: gcc
      before_script:
        - export CXX="g++-4.9"; CC="gcc-4.9";
        - echo $CXX; echo $CC;
    - os: osx
      compiler: clang   
    - os: osx
      compiler: gcc 
before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-4.9"; CC="gcc-4.9"; echo $CXX;echo $CC ; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - python-numpy
    - libgl1-mesa-dev
    - libgl1-mesa-glx
before_script:
  - pip install numpy
  - git clone https://github.com/mivp/LavaVuTesting
  - export DISPLAY=:99.0
  - export GALLIUM_DRIVER="llvmpipe"
    #  - sh -e /etc/init.d/xvfb start
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3 # give xvfb some time to start
  - export PYTHONPATH=$PYTHONPATH:`pwd`
script:
  - make LIBPNG=1 -j2
  - cd LavaVuTesting
  - python runall.py echo verbose
after_script:
  - cd ..
  - pwd
  - ls -la ./bin
