{% set name = "lavavu" %}
{% set version = "1.6.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/lavavu/LavaVu.git
  git_rev: condabuild #1.6.1
  git_depth: 1 # (Defaults to -1/not shallow)

#source:
#  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
#  sha256: 5b818b28c8e9e224dc75cfb35d48686f579eef5ab5a232585b1e3065ad34df32

build:
  number: 0
  entry_points:
    - LV = lavavu.__main__:main
    - LavaVu = lavavu.__main__:main
  #script: LV_OSMESA=1 {{ PYTHON }} -m pip install . -vv
  #script: {{ PYTHON }} -m pip install -vv $(../setup.py wheelname)

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxfixes-devel') }}  # [linux]
    - pip
  host:
    - python
    #- glfw
    - libglu  # [linux]
    #- mesalib  # [linux]
    #- ffmpeg
    #- sqlite
    #- libtiff
    - numpy >=1.11
    - jupyter-server-proxy
    - aiohttp

test:
  # Tests require visual context not present on CIs
  #test:
  #  requires:
  #    - {{ cdt('mesa-libgl-devel') }}  # [linux]
  #    - {{ cdt('mesa-dri-drivers') }}  # [linux]
  imports:
    - lavavu
  commands:
    #This will not work on CI without opengl context / osmesa
    #- printf "test\nimage\nquit" | LavaVu
    - python -c "import lavavu; print(lavavu.__version__);"

about:
  home: "https://github.com/lavavu/LavaVu"
  license: "GNU Lesser General Public v3 (LGPLv3)"
  license_family: LGPL
  summary: "Python interface to LavaVu OpenGL 3D scientific visualisation utilities"
  doc_url: https://lavavu.github.io/Documentation/ 

extra:
  recipe-maintainers:
    - rbeucher, okaluza
