name: Docker Image CI and publish notebook container
# Build on every branch push, tag push, and pull request change where tag matches a version release
on:
  workflow_dispatch:
  push:
    tags:
     - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@master

    - name: update jupyter dependencies with repo2docker
      uses: machine-learning-apps/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.LAVAVU_PACKAGES }}
        DOCKER_REGISTRY: "ghcr.io"
        IMAGE_NAME: "lavavu/lavavu" # this overrides the image name
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
