# - Creates a release on matching tag push (disabled for now)
# - builds new emscripten wasm
# - uploads as release assets
#
# https://github.com/lavavu/LavaVu/releases/latest/download/LavaVu.wasm
# https://github.com/lavavu/LavaVu/releases/latest/download/LavaVu-amalgamated.js
# https://github.com/lavavu/LavaVu/releases/latest/download/LavaVu.data
# https://github.com/lavavu/LavaVu/releases/latest/download/LavaVu-amalgamated.css

name: Release-Emscripten-Build

# Build on every branch push, tag push, and pull request change where tag matches a version release
on: [push]
#    tags:
#     - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v7

      - name: Verify
        run: emcc -v

      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install prereqs
        run: python -m pip install -r requirements.txt
      - name: Build/install
        run: make emscripten

      #- name: Create Release
      #  id: create_release
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: ${{ github.ref }}
      #    release_name: Release ${{ github.ref }}
      #    draft: false
      #    prerelease: false

      - name: Zip
        run: |
          zip --junk-paths LavaVu-web ./lavavu/html/webview.html ./lavavu/html/LavaVu.wasm ./lavavu/html/LavaVu.data ./lavavu/html/LavaVu-amalgamated.js ./lavavu/html/LavaVu-amalgamated.css

      - name: Upload Emscripten
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: LavaVu-web.zip
          asset_name: LavaVu-web.zip
          #tag: ${{ github.ref }} #Use current tag/ref
          tag: 1.6.7 #Hard code tag for testing
          overwrite: true
          #body: "This is my release text"
          release_name: v${{ github.ref }}

      - name: Push files to lavavu.github.io
        env:
          API_TOKEN_GITHUB: ${{ secrets.LAVAVU_PUSH }}
        run: |
          git config --global user.name "okaluza"
          git config --global user.email "owen.kaluza@monash.edu"
          git clone --depth 1 --single-branch --branch main https://$API_TOKEN_GITHUB@github.com/lavavu/lavavu.github.io
          cd lavavu.github.io
          git checkout main
          cp ../lavavu/html/webview.html .
          cp ../lavavu/html/LavaVu.wasm .
          cp ../lavavu/html/LavaVu.data .
          cp ../lavavu/html/LavaVu-amalgamated.js .
          cp ../lavavu/html/LavaVu-amalgamated.css .
          git stage *
          git commit -m "Update LavaVu emscripten release"
          git push

