name: WheelDeployTest

on:
  push

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_BUILD_VERBOSITY: 3
      CIBW_BUILD: cp312-*
      #CIBW_BUILD: cp311-* cp312-*
      #CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-*
      #CIBW_TEST_COMMAND: python3 -m doctest -v lavavu/lavavu.py
      #CIBW_REPAIR_WHEEL_COMMAND_MACOS: delocate-listdeps {wheel} && delocate-wheel -v -w {dest_dir} {wheel}
      CIBW_ENVIRONMENT: LV_LIB_DIRS=${HOME}/lib LV_INC_DIRS=${HOME}/include
      CIBW_BEFORE_BUILD_LINUX: cd ~ && curl -O -L https://github.com/lavavu/LavaVu/releases/latest/download/ffmpeg-mini.zip && unzip -o ffmpeg-mini.zip && dnf install -y --nogpgcheck libtiff-devel
      CIBW_BEFORE_BUILD_MACOS: brew install ffmpeg && sudo ln -s /opt/homebrew/lib /usr/local/lib && sudo ln -s /opt/homebrew/include /usr/local/include
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
    strategy:
      matrix:
        # MacOS 13 runner is x86_64, 14 is arm64
        # (https://cibuildwheel.pypa.io/en/stable/faq/#how)
        #os: [macos-13, macos-14]
        os: [macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.22.0

      # https://github.com/pypa/cibuildwheel/issues/563
      - name: Set macOS deployment target
        run: echo "MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion | cut -d '.' -f 1-2)" >> $GITHUB_ENV

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl


