name: Multi-build

on:
  workflow_dispatch:
  push:

jobs:
  build_wheels:
    name: Build lavavu wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_BUILD_VERBOSITY: 3
      CIBW_SKIP: *-musllinux_* *-manylinux_i686
      #CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*
      CIBW_BUILD: cp312-*
      CIBW_ENVIRONMENT: >
        LV_LIB_DIRS=/usr/local/lib64:/usr/lib64:${HOME}/lib 
        LV_INC_DIRS=${HOME}/include
      CIBW_BEFORE_BUILD_LINUX: >
        rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux &&
        dnf install -y libtiff-devel mesa-libOSMesa-devel && echo {package} &&
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.22.0

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl


