# Builds a special version of the wheel including OSMesa for use on Gadi
name: OSMesaDeploy

# Build on every branch push, tag push, and pull request change where tag matches a version release
on:
  workflow_dispatch:
  push:
    tags:
     - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_BUILD_VERBOSITY: 1 #3
      CIBW_SKIP: cp*-win32 *-musllinux_* *-manylinux_i686
      CIBW_BUILD: cp313-*
      CIBW_ENVIRONMENT: >
        LV_LIB_DIRS=/usr/local/lib64:/usr/lib64:${HOME}/lib
        LV_INC_DIRS=${HOME}/include
        LV_MIN_DEPS=1
        LV_PACKAGE=lavavu-osmesa
        LV_OSMESA=1
        LV_ECHO_FAIL=1
        LV_ARGS="-v"
      CIBW_BEFORE_BUILD_LINUX: >
        rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux &&
        dnf install -y libtiff-devel mesa-libOSMesa-devel && echo {package}
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
      #CIBW_TEST_COMMAND: >
      #  export LV_CONTEXT=osmesa &&
      #  git clone --depth 1 https://github.com/lavavu/Testing &&
      #  cd Testing &&
      #  python runall.py

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.2

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

