on: [push]

jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: [3.8] #[3.6, 3.7, 3.8, 3.9]        
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Set up *nix dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r"
            sudo apt-get install mesa-utils libgl1-mesa-dev
          fi
      - name: Install prereqs
        run: python -m pip install -r requirements.txt
      - name: Build/install
        env:
          LV_OSMESA: 1
        run: python setup.py install
      - name: Run headless test (linux only)
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            git clone --depth 1 https://github.com/lavavu/Testing
            cd Testing
            export LV_ECHO_FAIL=1
            export LV_ARGS="-v"
            python runall.py
            cd ..
          fi
