name: TestTheTests

on:
  push

jobs:
  test:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: [3.6] #, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@master
        with:
          repository: LavaVu/Testing
          path: Testing
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install wheel
        run: python -m pip install lavavu
      - name: Run headless test (linux only)
        env:
          LV_ECHO_FAIL: "1"
          LV_ARGS: "-v"
        #This needs to run with xvfb
        uses: GabrielBB/xvfb-action@v1
        if: runner.os == 'Linux'
        with:
          working-directory: ./Testing #optional
          run: python runall.py

