name: WheelTest

on:
  workflow_dispatch:
  #push:

jobs:
  test:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-13, macos-14]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@master
        with:
          repository: LavaVu/Testing
          path: Testing
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install wheel
        run: python -m pip install --only-binary=lavavu lavavu
      - name: Run tests
        env:
          LV_CONTEXT: moderngl
          LV_ECHO_FAIL: 1
          LV_ARGS: -v
        run: >
          pip install moderngl &&
          python runall.py
