name: Test

#Run on pushed commits but not tags
#https://github.community/t/dont-run-on-tag-creation/137469/7
on:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Set up *nix dependencies
        if: runner.os == 'Linux'
        run: |
          sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r"
          sudo apt-get update
          sudo apt-get install -y --allow-downgrades libosmesa6=20.0.4-2ubuntu1 libosmesa6-dev=20.0.4-2ubuntu1 libglapi-mesa=20.0.4-2ubuntu1 mesa-common-dev=20.0.4-2ubuntu1 libglx-mesa0=20.0.4-2ubuntu1 libgl1-mesa-dri=20.0.4-2ubuntu1 libgl-dev=1.3.1-1 libglx-dev=1.3.1-1 libgl1=1.3.1-1 libglx0=1.3.1-1 libglvnd0=1.3.1-1
      - name: Install prereqs
        run: python -m pip install -r requirements.txt
      - name: Build/install
        run: LV_OSMESA=1 python setup.py install
      - name: Run headless test (linux only)
        if: runner.os == 'Linux'
        run: |
          git clone --depth 1 https://github.com/lavavu/Testing
          cd Testing
          export LV_ECHO_FAIL=1
          export LV_ARGS="-v"
          python runall.py
          cd ..

