name: Test

#Run on pushed commits but not tags
#https://github.community/t/dont-run-on-tag-creation/137469/7
on:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest] #, macos-latest] #Re-enable this at some point after duplicating the problem on 3.9+ (seems to attempt to install itself as a dependency and fails)
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Set up *nix dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libosmesa6 libosmesa6-dev libglapi-mesa mesa-common-dev libglx-mesa0 libgl1-mesa-dri libgl-dev libglx-dev libgl1 libglx0 libglvnd0
      - name: Install prereqs
        run: python -m pip install -r requirements.txt
      - name: Build/install
        run: LV_OSMESA=1 python -m pip install .
      - name: Run headless test (linux only)
        if: runner.os == 'Linux'
        run: |
          git clone --depth 1 https://github.com/lavavu/Testing
          cd Testing
          export LV_ECHO_FAIL=1
          export LV_ARGS="-v"
          python runall.py
          cd ..

